# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../4林瞒/project1.o
LINKOBJ  = ../4林瞒/project1.o
LIBS     = -L"C:/Users/hyunl/Dev-Cpp/MinGW64/lib" -L"C:/Users/hyunl/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/hyunl/Dev-Cpp/MinGW64/include" -I"C:/Users/hyunl/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/hyunl/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/hyunl/Dev-Cpp/MinGW64/include" -I"C:/Users/hyunl/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/hyunl/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/hyunl/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = week04.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

../4林瞒/project1.o: ../4林瞒/project1.c
	$(CC) -c ../4林瞒/project1.c -o ../4林瞒/project1.o $(CFLAGS)
